2023-12-18 00:08:39.416 EET [7160] LOG:  checkpoint starting: time
2023-12-18 00:08:44.380 EET [7160] LOG:  checkpoint complete: wrote 50 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.904 s, sync=0.048 s, total=4.964 s; sync files=41, longest=0.003 s, average=0.002 s; distance=166 kB, estimate=4112 kB; lsn=0/1A914E8, redo lsn=0/1A914B0
2023-12-18 00:33:39.410 EET [7160] LOG:  checkpoint starting: time
2023-12-18 00:33:40.730 EET [7160] LOG:  checkpoint complete: wrote 14 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.294 s, sync=0.015 s, total=1.321 s; sync files=10, longest=0.002 s, average=0.002 s; distance=34 kB, estimate=3704 kB; lsn=0/1A9A028, redo lsn=0/1A99FD8
2023-12-18 00:38:29.911 EET [3792] ERROR:  syntax error at or near "POSITION" at character 60
2023-12-18 00:38:29.911 EET [3792] STATEMENT:  ALTER TABLE dota2_heroes
	ALTER COLUMN hero_description SET POSITION AFTER hero_name;
2023-12-18 00:38:45.801 EET [3792] ERROR:  syntax error at or near "AFTER" at character 60
2023-12-18 00:38:45.801 EET [3792] STATEMENT:  ALTER TABLE dota2_heroes
	ALTER COLUMN hero_description SET AFTER hero_name;
2023-12-18 00:46:17.290 EET [4076] ERROR:  relation "public.dota2_heroes" does not exist at character 15
2023-12-18 00:46:17.290 EET [4076] STATEMENT:  SELECT * FROM public.dota2_heroes
	ORDER BY hero_id ASC;
2023-12-18 00:47:12.110 EET [4284] FATAL:  password authentication failed for user "csbc"
2023-12-18 00:47:12.110 EET [4284] DETAIL:  User "csbc" has no password assigned.
	Connection matched file "C:/Program Files/PostgreSQL/16/data/pg_hba.conf" line 117: "host    all             all             ::1/128                 scram-sha-256"
2023-12-18 00:53:39.778 EET [7160] LOG:  checkpoint starting: time
2023-12-18 00:53:43.444 EET [7160] LOG:  checkpoint complete: wrote 37 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=3.624 s, sync=0.031 s, total=3.667 s; sync files=26, longest=0.003 s, average=0.002 s; distance=170 kB, estimate=3351 kB; lsn=0/1AC4840, redo lsn=0/1AC4808
2023-12-18 00:54:59.036 EET [3456] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2023-12-18 13:10:12.065 EET [14476] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2023-12-18 13:10:12.065 EET [4188] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2023-12-18 13:10:17.361 EET [1320] ERROR:  canceling statement due to user request
2023-12-18 13:10:17.379 EET [7160] LOG:  shutting down
2023-12-18 13:10:17.381 EET [7160] LOG:  checkpoint starting: shutdown immediate
2023-12-18 13:10:17.395 EET [7160] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.001 s, total=0.017 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=3015 kB; lsn=0/1AC48F0, redo lsn=0/1AC48F0
